// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module "@analogjs/router" {
  interface AnalogRouteTable {
    "/": {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    "/about": {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: "page" | "content";
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/index": AnalogGeneratedRouteRecord<"/index", "/", "/", null, readonly []>;
  "/about": AnalogGeneratedRouteRecord<"/about", "about", "/about", null, readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/index"];
  "/about": AnalogFileRoutesById["/about"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/index": {
      id: "/index",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/index"],
    "/about": {
      id: "/about",
      path: "about",
      fullPath: "/about",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/about.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/about"],
  },
  byFullPath: {
    "/": "/index",
    "/about": "/about",
  },
} as const;
