packages:
  - packages/*
  - examples/*
  - docs
  - e2e

catalog:
  next: ^16.2.0
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@types/node": ^22.0.0
  typescript: ^5.7.0
  vite: ^8.0.0
  tsdown: ^0.21.0
  hono: ^4.7.0
  "@hono/node-server": ^1.14.0
  tsx: ^4.19.0
  "@lazarv/react-server": 0.0.0-experimental-a0c7b63-20260415-0532bb4e
  "@tanstack/react-start": ^1.120.0
  "@tanstack/react-router": ^1.120.0
  "@tanstack/react-router-devtools": ^1.120.0
  "@vitejs/plugin-react": ^6.0.0
  nitro: ^3.0.260311-beta
  ng-packagr: ^20.0.0
  "@angular/compiler-cli": ^20.2.0
  "@angular/compiler": ^20.2.0

onlyBuiltDependencies:
  - esbuild
  - sharp
