// Type declarations for Module Federation remote imports.
// In a real project these are auto-generated by @module-federation/enhanced.

declare module "mf_remote/Counter" {
  import type { StoreProxy } from "@virtual-frame/store";

  export const Counter: React.FC<{
    label?: string;
    store?: StoreProxy;
  }>;

  export default { Counter };
}
